from . import account_move
from . import res_partner
from . import product_pricelist
from . import commission
from . import soa
from . import repair_order
from . import purchase_order
from . import sale_order
from . import sale_order_import
from . import stock_production_lot
from . import vessel
from . import voyage
from . import conves
from . import port_code
from . import port_of_call
from . import slot_owner
from . import terminal_code
from . import hs_code
from . import product_line_set
from . import cro
from . import product_template
from . import ir_reports
from . import stock_move
from . import stock_location
from . import res_currencies
from . import detention_formula
from . import group_code
from . import kpbc_code
from . import package_code
from . import report_excel
from . import hr_expense
